"use client";

import React, { useState, useEffect, useCallback } from "react";
import { Calendar, Clock, ArrowRight, Search, Eye, BookOpen, ChevronRight, Tag, X, Plus, Save, Trash2, Edit3, Image, AlignLeft, Hash, FileText, ChevronDown, ChevronUp, ExternalLink } from "lucide-react";

// ─── Types ──────────────────────────────────────────────────────────────────

interface BlogPost {
  id: string;
  slug: string;
  title: string;
  excerpt: string;
  content: string;
  author: string;
  authorRole: string;
  date: string;
  readTime: string;
  category: string;
  tags: string[];
  coverImage: string;
  views: number;
  published: boolean;
  seoTitle: string;
  seoDescription: string;
  schemaType: "Article" | "BlogPosting" | "TechArticle";
}

type ActiveView = "listing" | "article" | "admin" | "write";

// ─── Helpers ─────────────────────────────────────────────────────────────────

function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^\w\s-]/g, "")
    .replace(/\s+/g, "-")
    .replace(/-+/g, "-")
    .trim()
    .slice(0, 80);
}

function generateId(): string {
  return Math.random().toString(36).slice(2, 10);
}

function estimateReadTime(content: string): string {
  const words = content.replace(/<[^>]+>/g, "").split(/\s+/).length;
  const mins = Math.max(1, Math.round(words / 200));
  return `${mins} min`;
}

function formatDate(iso: string): string {
  return new Date(iso).toLocaleDateString("en-US", {
    year: "numeric",
    month: "short",
    day: "numeric",
  });
}

function formatViews(n: number): string {
  return n >= 1000 ? `${(n / 1000).toFixed(1)}K` : String(n);
}

// ─── Schema.org JSON-LD generator ────────────────────────────────────────────

function generateStructuredData(post: BlogPost, siteUrl: string): string {
  const schema = {
    "@context": "https://schema.org",
    "@type": post.schemaType,
    headline: post.seoTitle || post.title,
    description: post.seoDescription || post.excerpt,
    image: post.coverImage,
    datePublished: post.date,
    dateModified: post.date,
    author: {
      "@type": "Person",
      name: post.author,
      jobTitle: post.authorRole,
    },
    publisher: {
      "@type": "Organization",
      name: "Bridge Homies",
      url: siteUrl,
    },
    url: `${siteUrl}/blog#${post.slug}`,
    keywords: post.tags.join(", "),
    articleSection: post.category,
    mainEntityOfPage: {
      "@type": "WebPage",
      "@id": `${siteUrl}/blog#${post.slug}`,
    },
  };
  return JSON.stringify(schema, null, 2);
}

// ─── Storage helpers ──────────────────────────────────────────────────────────

const STORAGE_KEY = "bh_blog_posts";

function loadPosts(): BlogPost[] {
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    if (!raw) return SEED_POSTS;
    const parsed: BlogPost[] = JSON.parse(raw);
    return parsed.length ? parsed : SEED_POSTS;
  } catch {
    return SEED_POSTS;
  }
}

function savePosts(posts: BlogPost[]): void {
  try {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(posts));
  } catch {
    // silent
  }
}

// ─── Seed data ────────────────────────────────────────────────────────────────

const SEED_POSTS: BlogPost[] = [
  {
    id: "seed1",
    slug: "ai-powered-web-development-2025",
    title: "AI-Powered Web Development: What's Changed in 2025",
    excerpt:
      "From code generation to automated testing, AI has fundamentally reshaped how modern web applications are built. Here's what every developer needs to know.",
    content: `<p>Artificial intelligence is no longer a futuristic concept in web development — it's the daily toolkit. Over the past year, the gap between what a solo developer can ship and what an entire team used to ship has compressed dramatically.</p>

<h2>Code generation has gone mainstream</h2>
<p>Tools like GitHub Copilot, Cursor, and Claude Code now write boilerplate, suggest refactors, and catch bugs before they reach production. The developer's role is shifting toward architecture decisions, prompt engineering, and quality validation.</p>

<h2>Testing is no longer an afterthought</h2>
<p>AI-assisted test generation means you can describe a feature in plain English and get a full test suite back in seconds. This lowers the barrier for teams that historically skipped coverage.</p>

<h2>What this means for agencies like ours</h2>
<p>At Bridge Homies, we've integrated AI tooling at every layer of our stack — from design mockups generated by Figma AI to deployment pipelines monitored by intelligent observability tools. The result: faster delivery, higher quality, and more budget left over for the work that actually requires human creativity.</p>`,
    author: "Danyaal Majid",
    authorRole: "CTO & Director",
    date: new Date().toISOString(),
    readTime: "6 min",
    category: "AI & Development",
    tags: ["AI", "Web Development", "Next.js", "Automation"],
    coverImage:
      "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800&h=500&fit=crop",
    views: 2400,
    published: true,
    seoTitle: "AI-Powered Web Development in 2025 | Bridge Homies",
    seoDescription:
      "How AI tools are reshaping modern web development workflows in 2025. Insights from the Bridge Homies engineering team.",
    schemaType: "TechArticle",
  },
  {
    id: "seed2",
    slug: "fbr-integration-lessons-learned",
    title: "FBR Integration: Lessons Learned Building Aierpify",
    excerpt:
      "Integrating with Pakistan's Federal Board of Revenue API is non-trivial. We share the real challenges, edge cases, and solutions we found building our ERP product.",
    content: `<p>When we started building Aierpify, we underestimated how complex FBR integration would be. This post captures the lessons so other teams don't repeat our mistakes.</p>

<h2>Authentication is not straightforward</h2>
<p>FBR uses a certificate-based authentication flow that differs from standard OAuth. Managing certificate rotation in production required custom middleware we hadn't planned for.</p>

<h2>Rate limits and retry logic matter</h2>
<p>The FBR API enforces strict rate limits, especially during peak filing hours. We built an exponential back-off queue that batches invoice submissions, which reduced failed submissions by 94%.</p>

<h2>Data validation must happen client-side first</h2>
<p>Every validation error from FBR costs a network round-trip and confuses users. We mirrored their validation schema locally so users see errors instantly, before any API call is made.</p>

<h2>Lessons for your integration</h2>
<p>Plan for certificate management from day one. Build retry logic early. Mirror validation on the client. And always test against the FBR sandbox environment for at least two weeks before going live.</p>`,
    author: "Muhammad Bin Asif",
    authorRole: "Founder & Director",
    date: new Date(Date.now() - 7 * 86400000).toISOString(),
    readTime: "8 min",
    category: "Engineering",
    tags: ["FBR", "ERP", "Pakistan", "API Integration"],
    coverImage:
      "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&h=500&fit=crop",
    views: 1800,
    published: true,
    seoTitle: "FBR API Integration Lessons | Aierpify by Bridge Homies",
    seoDescription:
      "Real challenges and solutions from building an FBR-integrated invoicing system. Certificate auth, rate limits, validation mirroring.",
    schemaType: "TechArticle",
  },
];

// ─── Admin password (demo only — replace with real auth) ─────────────────────

const ADMIN_PASS = "bridgehomies2025";

// ─── Empty post template ──────────────────────────────────────────────────────

function emptyPost(): BlogPost {
  return {
    id: generateId(),
    slug: "",
    title: "",
    excerpt: "",
    content: "",
    author: "",
    authorRole: "",
    date: new Date().toISOString(),
    readTime: "1 min",
    category: "",
    tags: [],
    coverImage: "",
    views: 0,
    published: false,
    seoTitle: "",
    seoDescription: "",
    schemaType: "BlogPosting",
  };
}

// ─── Subcomponents ────────────────────────────────────────────────────────────

function ArticleCard({
  post,
  onOpen,
  featured = false,
}: {
  post: BlogPost;
  onOpen: (post: BlogPost) => void;
  featured?: boolean;
}) {
  return (
    <article
      onClick={() => onOpen(post)}
      className={`group cursor-pointer bg-white dark:bg-gray-900 border border-gray-200 dark:border-gray-700 rounded-xl overflow-hidden hover:border-purple-400 hover:shadow-lg transition-all duration-200 ${
        featured ? "md:col-span-2" : ""
      }`}
      itemScope
      itemType="https://schema.org/BlogPosting"
    >
      <meta itemProp="headline" content={post.seoTitle || post.title} />
      <meta itemProp="description" content={post.seoDescription || post.excerpt} />
      <meta itemProp="datePublished" content={post.date} />
      <meta itemProp="author" content={post.author} />

      <div className={`relative overflow-hidden ${featured ? "h-64" : "h-48"}`}>
        <img
          src={post.coverImage || "https://images.unsplash.com/photo-1488590528505-98d2b5aba04b?w=800&h=400&fit=crop"}
          alt={post.title}
          className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-500"
          loading="lazy"
        />
        <div className="absolute inset-0 bg-gradient-to-t from-black/60 to-transparent" />
        <span className="absolute top-3 left-3 bg-purple-600 text-white text-xs font-semibold px-2.5 py-1 rounded-full">
          {post.category}
        </span>
      </div>

      <div className="p-5">
        <h2
          className="font-semibold text-gray-900 dark:text-white text-lg leading-snug mb-2 group-hover:text-purple-600 transition-colors line-clamp-2"
          itemProp="name"
        >
          {post.title}
        </h2>
        <p className="text-sm text-gray-500 dark:text-gray-400 line-clamp-2 mb-4">
          {post.excerpt}
        </p>

        <div className="flex items-center justify-between text-xs text-gray-400 dark:text-gray-500">
          <div className="flex items-center gap-3">
            <span className="flex items-center gap-1">
              <Calendar className="w-3.5 h-3.5" />
              {formatDate(post.date)}
            </span>
            <span className="flex items-center gap-1">
              <Clock className="w-3.5 h-3.5" />
              {post.readTime}
            </span>
          </div>
          <span className="flex items-center gap-1">
            <Eye className="w-3.5 h-3.5" />
            {formatViews(post.views)}
          </span>
        </div>
      </div>
    </article>
  );
}

function ArticleView({
  post,
  onBack,
  relatedPosts,
}: {
  post: BlogPost;
  onBack: () => void;
  relatedPosts: BlogPost[];
}) {
  const siteUrl = typeof window !== "undefined" ? window.location.origin : "https://bridgehomies.com";
  const structuredData = generateStructuredData(post, siteUrl);

  return (
    <div className="min-h-screen">
      {/* Inject structured data */}
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: structuredData }}
      />

      {/* Hero */}
      <div className="relative h-72 md:h-96 overflow-hidden">
        <img
          src={post.coverImage || "https://images.unsplash.com/photo-1488590528505-98d2b5aba04b?w=1200&h=600&fit=crop"}
          alt={post.title}
          className="w-full h-full object-cover"
        />
        <div className="absolute inset-0 bg-gradient-to-t from-black/80 via-black/40 to-transparent" />
        <div className="absolute bottom-0 left-0 right-0 p-6 md:p-10 max-w-4xl mx-auto">
          <button
            onClick={onBack}
            className="flex items-center gap-1.5 text-white/70 hover:text-white text-sm mb-4 transition-colors"
          >
            <ChevronRight className="w-4 h-4 rotate-180" />
            All articles
          </button>
          <span className="bg-purple-600 text-white text-xs font-semibold px-3 py-1 rounded-full mb-3 inline-block">
            {post.category}
          </span>
          <h1 className="text-2xl md:text-4xl font-bold text-white leading-tight" itemProp="headline">
            {post.title}
          </h1>
        </div>
      </div>

      {/* Meta */}
      <div className="max-w-4xl mx-auto px-6 py-6 flex flex-wrap items-center gap-6">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-full bg-purple-100 flex items-center justify-center text-purple-700 font-bold text-sm">
            {post.author.slice(0, 2).toUpperCase()}
          </div>
          <div>
            <p className="font-medium text-gray-900 dark:text-white text-sm">{post.author}</p>
            <p className="text-xs text-gray-500">{post.authorRole}</p>
          </div>
        </div>
        <div className="flex items-center gap-4 text-sm text-gray-500">
          <span className="flex items-center gap-1.5">
            <Calendar className="w-4 h-4" />
            {formatDate(post.date)}
          </span>
          <span className="flex items-center gap-1.5">
            <Clock className="w-4 h-4" />
            {post.readTime} read
          </span>
          <span className="flex items-center gap-1.5">
            <Eye className="w-4 h-4" />
            {formatViews(post.views)} views
          </span>
        </div>
      </div>

      {/* Content */}
      <div className="max-w-3xl mx-auto px-6 pb-16">
        <div
          className="prose prose-gray prose-lg max-w-none
            prose-headings:font-semibold prose-headings:text-gray-900
            prose-h2:text-2xl prose-h2:mt-10 prose-h2:mb-4 prose-h2:border-b prose-h2:border-purple-100 prose-h2:pb-3
            prose-p:text-gray-700 prose-p:leading-relaxed prose-p:mb-5
            prose-a:text-purple-600 prose-a:no-underline hover:prose-a:underline
            prose-strong:text-gray-900
            prose-ul:my-4 prose-li:text-gray-700
            prose-blockquote:border-l-4 prose-blockquote:border-purple-400 prose-blockquote:bg-purple-50 prose-blockquote:px-5 prose-blockquote:py-3 prose-blockquote:rounded-r-lg
            prose-code:bg-gray-100 prose-code:text-purple-700 prose-code:px-1.5 prose-code:py-0.5 prose-code:rounded prose-code:text-sm"
          dangerouslySetInnerHTML={{ __html: post.content }}
          itemProp="articleBody"
        />

        {/* Tags */}
        <div className="flex flex-wrap gap-2 mt-10 pt-6 border-t border-gray-200">
          {post.tags.map((tag) => (
            <span
              key={tag}
              className="px-3 py-1 bg-purple-50 border border-purple-200 rounded-full text-sm font-medium text-purple-700"
            >
              #{tag}
            </span>
          ))}
        </div>

        {/* Author box */}
        <div className="mt-10 p-6 bg-gray-50 dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-xl">
          <div className="flex items-center gap-4 mb-3">
            <div className="w-14 h-14 rounded-full bg-purple-200 flex items-center justify-center text-purple-800 font-bold">
              {post.author.slice(0, 2).toUpperCase()}
            </div>
            <div>
              <p className="font-semibold text-gray-900 dark:text-white">{post.author}</p>
              <p className="text-sm text-gray-500">{post.authorRole} · Bridge Homies</p>
            </div>
          </div>
        </div>

        {/* Related */}
        {relatedPosts.length > 0 && (
          <div className="mt-14">
            <h3 className="text-xl font-semibold text-gray-900 dark:text-white mb-6">
              Continue reading
            </h3>
            <div className="grid sm:grid-cols-2 gap-5">
              {relatedPosts.map((rp) => (
                <div
                  key={rp.id}
                  onClick={() => {
                    window.history.pushState({}, "", `/blog#${rp.slug}`);
                    window.scrollTo({ top: 0, behavior: "smooth" });
                  }}
                  className="group cursor-pointer bg-white dark:bg-gray-900 border border-gray-200 dark:border-gray-700 rounded-xl overflow-hidden hover:border-purple-400 transition-all"
                >
                  <div className="h-36 overflow-hidden">
                    <img
                      src={rp.coverImage}
                      alt={rp.title}
                      className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-500"
                    />
                  </div>
                  <div className="p-4">
                    <p className="text-xs text-purple-600 font-semibold mb-1">{rp.category}</p>
                    <h4 className="text-sm font-medium text-gray-900 dark:text-white line-clamp-2 group-hover:text-purple-600 transition-colors">
                      {rp.title}
                    </h4>
                    <p className="text-xs text-gray-400 mt-2">{rp.readTime} read</p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}
      </div>
    </div>
  );
}

// ─── Write / Edit Panel ───────────────────────────────────────────────────────

function WritePanel({
  initial,
  onSave,
  onCancel,
}: {
  initial: BlogPost;
  onSave: (post: BlogPost) => void;
  onCancel: () => void;
}) {
  const [post, setPost] = useState<BlogPost>({ ...initial });
  const [tagInput, setTagInput] = useState("");
  const [seoOpen, setSeoOpen] = useState(false);
  const [sdOpen, setSdOpen] = useState(false);

  function set<K extends keyof BlogPost>(key: K, val: BlogPost[K]) {
    setPost((p) => {
      const next = { ...p, [key]: val };
      if (key === "title" && !initial.slug) {
        next.slug = slugify(String(val));
      }
      if (key === "content") {
        next.readTime = estimateReadTime(String(val));
      }
      return next;
    });
  }

  function addTag() {
    const t = tagInput.trim();
    if (t && !post.tags.includes(t)) {
      set("tags", [...post.tags, t]);
    }
    setTagInput("");
  }

  function removeTag(t: string) {
    set("tags", post.tags.filter((x) => x !== t));
  }

  const structuredDataPreview = generateStructuredData(
    post,
    typeof window !== "undefined" ? window.location.origin : "https://bridgehomies.com"
  );

  return (
    <div className="max-w-4xl mx-auto px-4 py-8">
      <div className="flex items-center justify-between mb-8">
        <button
          onClick={onCancel}
          className="flex items-center gap-2 text-gray-500 hover:text-gray-900 text-sm transition-colors"
        >
          <X className="w-4 h-4" />
          Cancel
        </button>
        <div className="flex items-center gap-3">
          <label className="flex items-center gap-2 text-sm text-gray-600 cursor-pointer select-none">
            <input
              type="checkbox"
              checked={post.published}
              onChange={(e) => set("published", e.target.checked)}
              className="rounded"
            />
            Publish
          </label>
          <button
            onClick={() => onSave(post)}
            className="flex items-center gap-2 bg-purple-600 hover:bg-purple-700 text-white text-sm font-medium px-4 py-2 rounded-lg transition-colors"
          >
            <Save className="w-4 h-4" />
            Save
          </button>
        </div>
      </div>

      {/* Cover Image */}
      <div className="mb-6">
        <label className="block text-xs font-semibold text-gray-500 uppercase tracking-wide mb-2">
          <Image className="w-3.5 h-3.5 inline mr-1" />
          Cover image URL
        </label>
        <input
          type="url"
          placeholder="https://images.unsplash.com/..."
          value={post.coverImage}
          onChange={(e) => set("coverImage", e.target.value)}
          className="w-full border border-gray-200 rounded-lg px-3 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-purple-400"
        />
        {post.coverImage && (
          <div className="mt-3 h-48 rounded-lg overflow-hidden">
            <img src={post.coverImage} alt="cover preview" className="w-full h-full object-cover" />
          </div>
        )}
      </div>

      {/* Category & Author row */}
      <div className="grid grid-cols-2 gap-4 mb-6">
        <div>
          <label className="block text-xs font-semibold text-gray-500 uppercase tracking-wide mb-2">Category</label>
          <input
            type="text"
            placeholder="e.g. Engineering"
            value={post.category}
            onChange={(e) => set("category", e.target.value)}
            className="w-full border border-gray-200 rounded-lg px-3 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-purple-400"
          />
        </div>
        <div>
          <label className="block text-xs font-semibold text-gray-500 uppercase tracking-wide mb-2">Schema type</label>
          <select
            value={post.schemaType}
            onChange={(e) => set("schemaType", e.target.value as BlogPost["schemaType"])}
            className="w-full border border-gray-200 rounded-lg px-3 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-purple-400"
          >
            <option value="BlogPosting">BlogPosting</option>
            <option value="Article">Article</option>
            <option value="TechArticle">TechArticle</option>
          </select>
        </div>
      </div>

      <div className="grid grid-cols-2 gap-4 mb-6">
        <div>
          <label className="block text-xs font-semibold text-gray-500 uppercase tracking-wide mb-2">Author name</label>
          <input
            type="text"
            placeholder="Muhammad Bin Asif"
            value={post.author}
            onChange={(e) => set("author", e.target.value)}
            className="w-full border border-gray-200 rounded-lg px-3 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-purple-400"
          />
        </div>
        <div>
          <label className="block text-xs font-semibold text-gray-500 uppercase tracking-wide mb-2">Author role</label>
          <input
            type="text"
            placeholder="Founder & Director"
            value={post.authorRole}
            onChange={(e) => set("authorRole", e.target.value)}
            className="w-full border border-gray-200 rounded-lg px-3 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-purple-400"
          />
        </div>
      </div>

      {/* Title */}
      <div className="mb-4">
        <label className="block text-xs font-semibold text-gray-500 uppercase tracking-wide mb-2">Title</label>
        <textarea
          placeholder="Write a compelling title…"
          value={post.title}
          onChange={(e) => set("title", e.target.value)}
          rows={2}
          className="w-full border border-gray-200 rounded-lg px-3 py-2.5 text-xl font-bold focus:outline-none focus:ring-2 focus:ring-purple-400 resize-none"
        />
      </div>

      {/* Slug */}
      <div className="mb-4">
        <label className="block text-xs font-semibold text-gray-500 uppercase tracking-wide mb-2">
          <Hash className="w-3.5 h-3.5 inline mr-1" />
          URL slug  <span className="font-normal text-gray-400 normal-case">(auto-generated, editable)</span>
        </label>
        <div className="flex items-center border border-gray-200 rounded-lg overflow-hidden focus-within:ring-2 focus-within:ring-purple-400">
          <span className="px-3 py-2.5 text-sm text-gray-400 bg-gray-50 border-r border-gray-200 select-none">
            /blog#
          </span>
          <input
            type="text"
            value={post.slug}
            onChange={(e) => set("slug", slugify(e.target.value))}
            className="flex-1 px-3 py-2.5 text-sm focus:outline-none"
          />
        </div>
      </div>

      {/* Excerpt */}
      <div className="mb-6">
        <label className="block text-xs font-semibold text-gray-500 uppercase tracking-wide mb-2">
          <AlignLeft className="w-3.5 h-3.5 inline mr-1" />
          Excerpt  <span className="font-normal text-gray-400 normal-case">(shown on listing page, used for AEO)</span>
        </label>
        <textarea
          placeholder="One or two sentences summarising the article. Make it answer a specific question."
          value={post.excerpt}
          onChange={(e) => set("excerpt", e.target.value)}
          rows={3}
          className="w-full border border-gray-200 rounded-lg px-3 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-purple-400 resize-none"
        />
      </div>

      {/* Tags */}
      <div className="mb-6">
        <label className="block text-xs font-semibold text-gray-500 uppercase tracking-wide mb-2">
          <Tag className="w-3.5 h-3.5 inline mr-1" />
          Tags
        </label>
        <div className="flex flex-wrap gap-2 mb-2">
          {post.tags.map((tag) => (
            <span
              key={tag}
              className="flex items-center gap-1 px-2.5 py-1 bg-purple-50 border border-purple-200 rounded-full text-xs text-purple-700"
            >
              #{tag}
              <button onClick={() => removeTag(tag)} className="hover:text-red-500 transition-colors">
                <X className="w-3 h-3" />
              </button>
            </span>
          ))}
        </div>
        <div className="flex gap-2">
          <input
            type="text"
            placeholder="Add a tag…"
            value={tagInput}
            onChange={(e) => setTagInput(e.target.value)}
            onKeyDown={(e) => e.key === "Enter" && addTag()}
            className="flex-1 border border-gray-200 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-purple-400"
          />
          <button
            onClick={addTag}
            className="px-3 py-2 bg-gray-100 hover:bg-gray-200 rounded-lg text-sm transition-colors"
          >
            Add
          </button>
        </div>
      </div>

      {/* Content */}
      <div className="mb-6">
        <label className="block text-xs font-semibold text-gray-500 uppercase tracking-wide mb-2">
          <FileText className="w-3.5 h-3.5 inline mr-1" />
          Content  <span className="font-normal text-gray-400 normal-case">(HTML supported — use &lt;h2&gt;, &lt;p&gt;, &lt;ul&gt;, &lt;strong&gt;, &lt;blockquote&gt;)</span>
        </label>
        <textarea
          placeholder={`<p>Start writing your article...</p>\n\n<h2>First section</h2>\n<p>Content here...</p>`}
          value={post.content}
          onChange={(e) => set("content", e.target.value)}
          rows={20}
          className="w-full border border-gray-200 rounded-lg px-3 py-2.5 text-sm font-mono focus:outline-none focus:ring-2 focus:ring-purple-400 resize-y"
        />
        <p className="text-xs text-gray-400 mt-1">
          Read time auto-calculated: <strong>{post.readTime}</strong>
        </p>
      </div>

      {/* SEO section */}
      <div className="mb-4 border border-gray-200 rounded-xl overflow-hidden">
        <button
          onClick={() => setSeoOpen((v) => !v)}
          className="w-full flex items-center justify-between p-4 text-sm font-semibold text-gray-700 bg-gray-50 hover:bg-gray-100 transition-colors"
        >
          <span className="flex items-center gap-2">
            <Search className="w-4 h-4 text-purple-500" />
            SEO & AEO settings
          </span>
          {seoOpen ? <ChevronUp className="w-4 h-4" /> : <ChevronDown className="w-4 h-4" />}
        </button>
        {seoOpen && (
          <div className="p-4 space-y-4">
            <div>
              <label className="block text-xs font-semibold text-gray-500 uppercase tracking-wide mb-2">
                SEO title  <span className="font-normal normal-case text-gray-400">(50–60 chars ideal)</span>
              </label>
              <input
                type="text"
                value={post.seoTitle}
                onChange={(e) => set("seoTitle", e.target.value)}
                placeholder={post.title}
                className="w-full border border-gray-200 rounded-lg px-3 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-purple-400"
              />
              <p className="text-xs text-gray-400 mt-1">{(post.seoTitle || post.title).length} chars</p>
            </div>
            <div>
              <label className="block text-xs font-semibold text-gray-500 uppercase tracking-wide mb-2">
                Meta description  <span className="font-normal normal-case text-gray-400">(140–160 chars ideal — answer a question for AEO)</span>
              </label>
              <textarea
                value={post.seoDescription}
                onChange={(e) => set("seoDescription", e.target.value)}
                placeholder={post.excerpt}
                rows={3}
                className="w-full border border-gray-200 rounded-lg px-3 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-purple-400 resize-none"
              />
              <p className="text-xs text-gray-400 mt-1">{(post.seoDescription || post.excerpt).length} chars</p>
            </div>

            {/* SERP preview */}
            <div className="bg-white border border-gray-200 rounded-lg p-4">
              <p className="text-xs font-semibold text-gray-400 uppercase tracking-wide mb-3">SERP preview</p>
              <p className="text-blue-700 text-base font-medium leading-tight">
                {post.seoTitle || post.title || "Your page title"}
              </p>
              <p className="text-green-700 text-xs mt-0.5">
                bridgehomies.com/blog#{post.slug || "article-slug"}
              </p>
              <p className="text-gray-600 text-sm mt-1 leading-relaxed">
                {post.seoDescription || post.excerpt || "Your meta description appears here — write it to answer a question."}
              </p>
            </div>
          </div>
        )}
      </div>

      {/* Structured data preview */}
      <div className="mb-8 border border-gray-200 rounded-xl overflow-hidden">
        <button
          onClick={() => setSdOpen((v) => !v)}
          className="w-full flex items-center justify-between p-4 text-sm font-semibold text-gray-700 bg-gray-50 hover:bg-gray-100 transition-colors"
        >
          <span className="flex items-center gap-2">
            <Hash className="w-4 h-4 text-green-500" />
            Schema.org JSON-LD preview
          </span>
          {sdOpen ? <ChevronUp className="w-4 h-4" /> : <ChevronDown className="w-4 h-4" />}
        </button>
        {sdOpen && (
          <pre className="p-4 text-xs font-mono text-gray-600 bg-gray-50 overflow-x-auto whitespace-pre-wrap">
            {structuredDataPreview}
          </pre>
        )}
      </div>

      <div className="flex justify-end gap-3 pt-4 border-t border-gray-200">
        <button
          onClick={onCancel}
          className="px-4 py-2 border border-gray-200 rounded-lg text-sm hover:bg-gray-50 transition-colors"
        >
          Cancel
        </button>
        <button
          onClick={() => onSave(post)}
          className="flex items-center gap-2 bg-purple-600 hover:bg-purple-700 text-white text-sm font-medium px-5 py-2 rounded-lg transition-colors"
        >
          <Save className="w-4 h-4" />
          Save article
        </button>
      </div>
    </div>
  );
}

// ─── Admin panel (list of all posts) ─────────────────────────────────────────

function AdminPanel({
  posts,
  onNew,
  onEdit,
  onDelete,
  onTogglePublish,
  onBack,
}: {
  posts: BlogPost[];
  onNew: () => void;
  onEdit: (post: BlogPost) => void;
  onDelete: (id: string) => void;
  onTogglePublish: (id: string) => void;
  onBack: () => void;
}) {
  return (
    <div className="max-w-5xl mx-auto px-4 py-8">
      <div className="flex items-center justify-between mb-8">
        <div>
          <h2 className="text-2xl font-bold text-gray-900">Blog admin</h2>
          <p className="text-sm text-gray-500 mt-0.5">{posts.length} articles total</p>
        </div>
        <div className="flex items-center gap-3">
          <button
            onClick={onBack}
            className="text-sm text-gray-500 hover:text-gray-900 transition-colors"
          >
            ← Back to blog
          </button>
          <button
            onClick={onNew}
            className="flex items-center gap-2 bg-purple-600 hover:bg-purple-700 text-white text-sm font-medium px-4 py-2 rounded-lg transition-colors"
          >
            <Plus className="w-4 h-4" />
            New article
          </button>
        </div>
      </div>

      <div className="space-y-3">
        {posts.map((p) => (
          <div
            key={p.id}
            className="flex items-center gap-4 bg-white border border-gray-200 rounded-xl p-4 hover:border-purple-300 transition-all"
          >
            <div className="w-16 h-12 rounded-lg overflow-hidden flex-shrink-0">
              <img
                src={p.coverImage || "https://images.unsplash.com/photo-1488590528505-98d2b5aba04b?w=128&h=80&fit=crop"}
                alt={p.title}
                className="w-full h-full object-cover"
              />
            </div>
            <div className="flex-1 min-w-0">
              <h3 className="font-medium text-gray-900 text-sm truncate">{p.title}</h3>
              <div className="flex items-center gap-3 mt-1">
                <span className="text-xs text-gray-400">{formatDate(p.date)}</span>
                <span className="text-xs text-purple-600">{p.category}</span>
                <span className="text-xs text-gray-400">{p.readTime}</span>
                <span
                  className={`text-xs px-2 py-0.5 rounded-full font-medium ${
                    p.published
                      ? "bg-green-50 text-green-700 border border-green-200"
                      : "bg-gray-50 text-gray-500 border border-gray-200"
                  }`}
                >
                  {p.published ? "Published" : "Draft"}
                </span>
              </div>
            </div>
            <div className="flex items-center gap-2 flex-shrink-0">
              <button
                onClick={() => onTogglePublish(p.id)}
                className="text-xs px-2.5 py-1.5 border border-gray-200 rounded-lg hover:bg-gray-50 transition-colors"
                title={p.published ? "Unpublish" : "Publish"}
              >
                {p.published ? "Unpublish" : "Publish"}
              </button>
              <button
                onClick={() => onEdit(p)}
                className="p-1.5 border border-gray-200 rounded-lg hover:bg-purple-50 hover:border-purple-300 transition-colors"
                title="Edit"
              >
                <Edit3 className="w-3.5 h-3.5 text-gray-600" />
              </button>
              <button
                onClick={() => {
                  if (confirm(`Delete "${p.title}"?`)) onDelete(p.id);
                }}
                className="p-1.5 border border-gray-200 rounded-lg hover:bg-red-50 hover:border-red-300 transition-colors"
                title="Delete"
              >
                <Trash2 className="w-3.5 h-3.5 text-red-400" />
              </button>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}

// ─── Login gate ───────────────────────────────────────────────────────────────

function AdminLogin({ onSuccess }: { onSuccess: () => void }) {
  const [pass, setPass] = useState("");
  const [error, setError] = useState(false);

  function submit(e: React.FormEvent) {
    e.preventDefault();
    if (pass === ADMIN_PASS) {
      sessionStorage.setItem("bh_admin", "1");
      onSuccess();
    } else {
      setError(true);
    }
  }

  return (
    <div className="min-h-[60vh] flex items-center justify-center">
      <div className="w-full max-w-sm">
        <h2 className="text-2xl font-bold text-gray-900 mb-6 text-center">Admin access</h2>
        <form onSubmit={submit} className="space-y-4">
          <input
            type="password"
            placeholder="Password"
            value={pass}
            onChange={(e) => { setPass(e.target.value); setError(false); }}
            autoFocus
            className={`w-full border ${error ? "border-red-400" : "border-gray-200"} rounded-lg px-4 py-3 text-sm focus:outline-none focus:ring-2 focus:ring-purple-400`}
          />
          {error && <p className="text-sm text-red-500">Incorrect password</p>}
          <button
            type="submit"
            className="w-full bg-purple-600 hover:bg-purple-700 text-white font-medium py-3 rounded-lg transition-colors"
          >
            Sign in
          </button>
        </form>
        <p className="text-xs text-center text-gray-400 mt-4">
          Demo password: <code className="bg-gray-100 px-1.5 py-0.5 rounded">bridgehomies2025</code>
        </p>
      </div>
    </div>
  );
}

// ─── Main BlogPortal ──────────────────────────────────────────────────────────

export default function BlogPortal() {
  const [posts, setPosts] = useState<BlogPost[]>([]);
  const [view, setView] = useState<ActiveView>("listing");
  const [activePost, setActivePost] = useState<BlogPost | null>(null);
  const [editingPost, setEditingPost] = useState<BlogPost | null>(null);
  const [searchQuery, setSearchQuery] = useState("");
  const [activeCategory, setActiveCategory] = useState("All");
  const [adminAuthed, setAdminAuthed] = useState(false);
  const [mounted, setMounted] = useState(false);

  // Load from localStorage
  useEffect(() => {
    const stored = loadPosts();
    setPosts(stored);
    setAdminAuthed(sessionStorage.getItem("bh_admin") === "1");
    setMounted(true);
  }, []);

  // Handle URL hash routing
  useEffect(() => {
    if (!mounted) return;

    function handleHashChange() {
      const hash = window.location.hash.slice(1); // remove #
      if (!hash) {
        setView("listing");
        setActivePost(null);
        return;
      }
      if (hash === "admin") {
        setView("admin");
        return;
      }
      // Try to find a post by slug
      const found = posts.find((p) => p.slug === hash);
      if (found) {
        setActivePost(found);
        setView("article");
        // Increment view counter
        setPosts((prev) => {
          const updated = prev.map((p) =>
            p.id === found.id ? { ...p, views: p.views + 1 } : p
          );
          savePosts(updated);
          return updated;
        });
      }
    }

    handleHashChange();
    window.addEventListener("hashchange", handleHashChange);
    return () => window.removeEventListener("hashchange", handleHashChange);
  }, [mounted, posts]);

  function openPost(post: BlogPost) {
    window.location.hash = post.slug;
  }

  function goBack() {
    window.location.hash = "";
    setView("listing");
    setActivePost(null);
  }

  // ── CRUD ──────────────────────────────────────────────────────────────────

  function handleSave(post: BlogPost) {
    setPosts((prev) => {
      const exists = prev.find((p) => p.id === post.id);
      const updated = exists
        ? prev.map((p) => (p.id === post.id ? post : p))
        : [...prev, post];
      savePosts(updated);
      return updated;
    });
    setView("admin");
    setEditingPost(null);
  }

  function handleDelete(id: string) {
    setPosts((prev) => {
      const updated = prev.filter((p) => p.id !== id);
      savePosts(updated);
      return updated;
    });
  }

  function handleTogglePublish(id: string) {
    setPosts((prev) => {
      const updated = prev.map((p) =>
        p.id === id ? { ...p, published: !p.published } : p
      );
      savePosts(updated);
      return updated;
    });
  }

  // ── Derived data ──────────────────────────────────────────────────────────

  const publishedPosts = posts.filter((p) => p.published);

  const categories = [
    "All",
    ...Array.from(new Set(publishedPosts.map((p) => p.category).filter(Boolean))),
  ];

  const filteredPosts = publishedPosts.filter((p) => {
    const matchCat = activeCategory === "All" || p.category === activeCategory;
    const q = searchQuery.toLowerCase();
    const matchQ =
      !q ||
      p.title.toLowerCase().includes(q) ||
      p.excerpt.toLowerCase().includes(q) ||
      p.tags.some((t) => t.toLowerCase().includes(q));
    return matchCat && matchQ;
  });

  const relatedPosts = activePost
    ? publishedPosts
        .filter(
          (p) =>
            p.id !== activePost.id &&
            p.tags.some((t) => activePost.tags.includes(t))
        )
        .slice(0, 2)
    : [];

  // ── Render ────────────────────────────────────────────────────────────────

  if (!mounted) return null;

  // Admin login gate
  if (view === "admin" && !adminAuthed) {
    return (
      <div className="min-h-screen bg-white dark:bg-gray-950">
        <AdminLogin onSuccess={() => { setAdminAuthed(true); setView("admin"); }} />
      </div>
    );
  }

  if (view === "admin") {
    return (
      <div className="min-h-screen bg-white dark:bg-gray-950">
        <AdminPanel
          posts={posts}
          onNew={() => { setEditingPost(emptyPost()); setView("write"); }}
          onEdit={(p) => { setEditingPost(p); setView("write"); }}
          onDelete={handleDelete}
          onTogglePublish={handleTogglePublish}
          onBack={goBack}
        />
      </div>
    );
  }

  if (view === "write" && editingPost) {
    return (
      <div className="min-h-screen bg-white dark:bg-gray-950">
        <WritePanel
          initial={editingPost}
          onSave={handleSave}
          onCancel={() => setView("admin")}
        />
      </div>
    );
  }

  if (view === "article" && activePost) {
    return (
      <div className="min-h-screen bg-white dark:bg-gray-950">
        <ArticleView post={activePost} onBack={goBack} relatedPosts={relatedPosts} />
      </div>
    );
  }

  // ── Listing view ──────────────────────────────────────────────────────────

  return (
    <div className="min-h-screen bg-white dark:bg-gray-950">
      {/* Blog header */}
      <div className="bg-gray-950 text-white py-16 px-6">
        <div className="max-w-5xl mx-auto">
          <h1 className="text-4xl md:text-5xl font-bold mb-3">Bridge Homies Blog</h1>
          <p className="text-gray-400 text-lg max-w-xl">
            Engineering insights, product updates, and digital strategy from our team.
          </p>

          {/* Search */}
          <div className="relative mt-8 max-w-md">
            <Search className="absolute left-3.5 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400" />
            <input
              type="text"
              placeholder="Search articles…"
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="w-full pl-10 pr-4 py-3 bg-gray-800 border border-gray-700 rounded-xl text-sm text-white placeholder-gray-500 focus:outline-none focus:border-purple-500 transition-colors"
            />
          </div>
        </div>
      </div>

      {/* Category tabs */}
      <div className="border-b border-gray-200 dark:border-gray-800 bg-white dark:bg-gray-950 sticky top-0 z-10">
        <div className="max-w-5xl mx-auto px-6 overflow-x-auto">
          <div className="flex items-center gap-1 py-3 whitespace-nowrap">
            {categories.map((cat) => (
              <button
                key={cat}
                onClick={() => setActiveCategory(cat)}
                className={`px-4 py-2 rounded-full text-sm font-medium transition-all ${
                  activeCategory === cat
                    ? "bg-purple-600 text-white"
                    : "text-gray-600 hover:bg-gray-100 dark:hover:bg-gray-800"
                }`}
              >
                {cat}
              </button>
            ))}
          </div>
        </div>
      </div>

      {/* Articles grid */}
      <div className="max-w-5xl mx-auto px-6 py-12">
        {filteredPosts.length === 0 ? (
          <div className="text-center py-16 text-gray-400">
            <BookOpen className="w-10 h-10 mx-auto mb-3 opacity-40" />
            <p className="text-lg">No articles found.</p>
          </div>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {filteredPosts.map((post, i) => (
              <ArticleCard
                key={post.id}
                post={post}
                onOpen={openPost}
                featured={i === 0 && filteredPosts.length >= 3}
              />
            ))}
          </div>
        )}
      </div>

      {/* Admin link */}
      <div className="border-t border-gray-200 dark:border-gray-800 py-6 px-6 text-center">
        <button
          onClick={() => { window.location.hash = "admin"; }}
          className="text-xs text-gray-400 hover:text-purple-600 transition-colors"
        >
          Admin
        </button>
      </div>
    </div>
  );
}